INSERT INTO Products (name, category, price, description, image)
VALUES ('Cosmic Down 40', 'sleepingbags', 129.95, 'Cosmic Down 40 Sleeping Bag','bag_1.jpg'),
      ('Atom', 'sleepingbags', 230.93, 'Atom Sleeping Bag', 'bag_2.jpg'),
      ('The North Face', 'sleepingbags', 189.00, 'Furnace 20 Sleeping Bag', 'bag_3.jpg'),
      ('Riff 15', 'sleepingbags', 419.95, 'Riff 15 Sleeping Bag', 'bag_4.jpg'),
      ('Co-op Magma 10', 'sleepingbags', 369.00, 'Co-op Magma 10 Sleeping Bag', 'bag_5.jpg'),
      ('Trestles 0', 'sleepingbags', 159.00, 'Trestles 0 Sleeping Bag', 'bag_6.jpg'),
      ('Kelty', 'sleepingbags', 169.95, 'Kelty Cosmic Down 20 Sleeping Bag', 'bag_7.jpg'),
      ('REI Co-op', 'sleepingbags', 99.95, 'REI Co-op Siesta 30 Sleeping Bag', 'bag_8.jpg'),
      ('NEMO', 'sleepingbags', 319.95, 'NEMO Disco 15 Sleeping Bag', 'bag_9.jpg'),
      ('Cabana Shelter', 'tents', 99.95, 'Cabana Shelter', 'tent_1.jpg'),
      ('Big Agnes', 'tents', 208.99, 'Big Agnes Frying Pan SL3 Tent with Footprint', 'tent_2.jpg'),
      ('Co-op Half Dome 2 Plus', 'tents', 229.00, 'Co-op Half Dome 2 Plus Tent', 'tent_3.jpg'),
      ('Co-op Kingdom 6', 'tents', 439.00, 'Co-op Kingdom 6 Tent', 'tent_4.jpg'),
      ('Assault 2', 'tents', 439.00, 'Assault 2 Tent', 'tent_5.jpg'),
      ('Battle Mountain 2', 'tents', 699.95, 'Battle Mountain 2 Tent', 'tent_6.jpg'),
      ('Big Agnes', 'tents', 399.99, 'Big Agnes Tiger Wall UL2 Tent', 'tent_7.jpg'),
      ('Marmot', 'tents', 169.00, 'Marmot Catalyst 2P Tent with Footprint', 'tent_8.jpg'),
      ('The North Face', 'tents', 199.00, 'The North Face Talus 2 Tent with Footprint', 'tent_9.jpg'),
      ('Manta AG 36 Hydration', 'backpacks', 175.00, 'Manta AG 36 Hydration Pack', 'pack_1.jpg'),
      ('Graviton 34', 'backpacks', 159.00, 'Graviton 34 Pack', 'pack_2.jpg'),
      ('Talon 6 Hydration', 'backpacks', 75.00, 'Talon 6 Hydration Waistpack', 'pack_3.jpg'),
      ('Kyte 46', 'backpacks', 180.00, 'Kyte 46 Pack', 'pack_4.jpg'),
      ('Trekker 65', 'backpacks', 179.95, 'Trekker 65 Pack', 'pack_5.jpg'),
      ('Kid Comfort Air', 'backpacks', 240.00, 'Kid Comfort Air Child Carrier', 'pack_6.jpg'),
      ('Osprey', 'backpacks', 270.00, 'Osprey Atmos AG 65 Pack', 'pack_7.jpg'),
      ('Gregory', 'backpacks', 299.95, 'Gregory Baltoro 65 Pack', 'pack_8.jpg'),
      ('REI Co-op', 'backpacks', 249.00, 'REI Co-op Traverse 65 Pack', 'pack_9.jpg');

-- Added a directory value to be able to navigate to the individual product page
