INSERT INTO Products (name, category, price, description, image)
VALUES ('Kelty', 'sleepingbags', 129.95, 'Cosmic Down 40 Sleeping Bag','bag_1.jpg'),
      ('Marmot', 'sleepingbags', 230.93, 'Atom Sleeping Bag', 'bag_2.jpg'),
      ('The North Face', 'sleepingbags', 189.00, 'Furnace 20 Sleeping Bag', 'bag_3.jpg'),
      ('NEMO', 'sleepingbags', 419.95, 'Riff 15 Sleeping Bag', 'bag_4.jpg'),
      ('REI Co-op', 'sleepingbags', 369.00, 'Magma 10 Sleeping Bag', 'bag_5.jpg'),
      ('Marmot', 'sleepingbags', 159.00, 'Trestles 0 Sleeping Bag', 'bag_6.jpg'),
      ('Kelty', 'sleepingbags', 169.95, 'Cosmic Down 20 Sleeping Bag', 'bag_7.jpg'),
      ('REI Co-op', 'sleepingbags', 99.95, 'Siesta 30 Sleeping Bag', 'bag_8.jpg'),
      ('NEMO', 'sleepingbags', 319.95, 'Disco 15 Sleeping Bag', 'bag_9.jpg'),
      ('Kelty', 'tents', 99.95, 'Cabana Shelter', 'tent_1.jpg'),
      ('Big Agnes', 'tents', 208.99, 'Frying Pan SL3 Tent with Footprint', 'tent_2.jpg'),
      ('REI Co-op', 'tents', 229.00, 'Half Dome 2 Plus Tent', 'tent_3.jpg'),
      ('REI Co-op', 'tents', 439.00, 'Kingdom 6 Tent', 'tent_4.jpg'),
      ('The North Face', 'tents', 439.00, 'Assault 2 Tent', 'tent_5.jpg'),
      ('Big Agnes', 'tents', 699.95, 'Battle Mountain 2 Tent', 'tent_6.jpg'),
      ('Big Agnes', 'tents', 399.99, 'Tiger Wall UL2 Tent', 'tent_7.jpg'),
      ('Marmot', 'tents', 169.00, 'Catalyst 2P Tent with Footprint', 'tent_8.jpg'),
      ('The North Face', 'tents', 199.00, 'Talus 2 Tent with Footprint', 'tent_9.jpg'),
      ('Osprey', 'backpacks', 175.00, 'Manta AG 36 Hydration Pack', 'pack_1.jpg'),
      ('Marmot', 'backpacks', 159.00, 'Graviton 34 Pack', 'pack_2.jpg'),
      ('Osprey', 'backpacks', 75.00, 'Talon 6 Hydration Waistpack', 'pack_3.jpg'),
      ('Osprey', 'backpacks', 180.00, 'Kyte 46 Pack', 'pack_4.jpg'),
      ('Kelty', 'backpacks', 179.95, 'Trekker 65 Pack', 'pack_5.jpg'),
      ('Deuter', 'backpacks', 240.00, 'Kid Comfort Air Child Carrier', 'pack_6.jpg'),
      ('Osprey', 'backpacks', 270.00, 'Atmos AG 65 Pack', 'pack_7.jpg'),
      ('Gregory', 'backpacks', 299.95, 'Baltoro 65 Pack', 'pack_8.jpg'),
      ('REI Co-op', 'backpacks', 249.00, 'Traverse 65 Pack', 'pack_9.jpg');

-- Added a directory value to be able to navigate to the individual product page
